//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Indicators = new HashSet<Indicator>();
        }
    
        public int Id { get; set; }
        public int Section_ID { get; set; }
        public Nullable<int> Number { get; set; }
        public string Text { get; set; }
        public int Category_ID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Indicator> Indicators { get; set; }
        public virtual Section Section { get; set; }
    }
}
